# Generated by Django 4.1.5 on 2023-01-18 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_remove_task_end_date_remove_task_start_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='content',
            new_name='description',
        ),
    ]
